### ISSUE TITLE
New experimental cohort management.

### ISSUE THREAD

**Issue by WardCunningham** [fedwiki/wiki-plugin-roster#1]
This plugin is offered for evaluation only. It works. It's safe. But it probably needs to do more before it meets the needs of educators offering classes supported by federated wiki.

![screen shot 2015-02-15 at 2 57 45 pm](https://cloud.githubusercontent.com/assets/12127/6205683/e47cf622-b52b-11e4-931e-ea1a1de567ab.png)

**Comment by WardCunningham** [comment]
I bring to this issue some email correspondence between Mike, Paul and myself.
See also https://github.com/fedwiki/wiki-plugin-activity/issues/4 mentioned several times here.

---

I can see the need for a file reference that can be updated as the happening progresses. I'd rather just use federation mechanisms but these are a struggle for new students so maybe something more magical is appropriate for maintaining the class roster.

I'm not committed to any of these ideas yet. But I thought we should be thinking of them before we add customization to Recent Changes.

---

We can do it without a central file, at least to start. The plugin can be placed on a page people fork, or the reference to the customized activity page could be placed on the orientation site. 

You say it would effect Recent Changes. I imagine that means it would not impact twins?

---

Yes, I'm imagining that a roster plugin on a Class Roster page would somehow work with the activity plugin on the Recent Changes page to give people the sort of experience they expect in a classroom, day one. This could be conversation-club-ish. I'm not sure what would be best.  I would also hope that whatever we do will works in a sensible way with neighborhoods and life-time learning. We have to forgive ourselves for not being exactly sure what we want. But whatever it is, people will demand to understand how it works and why we made it work that way.

---

Think about possible customisation of Recent Changes, and Conversations…

My idea was to have a conversation plugin, which would take a list of sites - a roster - and possibly a set of parameters to customise it by adding a time range and the number of participating sites needed to make it a conversation. I was thinking that it would to include sites in the conversation view without them being added to the neighbourhood, but if a site was in the neighbourhood the sitemap would be updated.

If this is going to be an extension to the activity plugin, and it should be, we need something to tell the plugin that it is creating a conversation view rather than recent pages. The recent changes plugin could have a double click action to edit its configuration. It would find its list of sites for a conversation by looking left for a roster - much like a graph looks for data - defaulting to using the neighbourhood if no roster is found. It would be nice if the flags in the roster could be animated, to provide some user feedback while sitemaps are being loaded.

**Comment by WardCunningham** [comment]
You have both raised issues that I have not thought through. I think we can make this useful, simple and empowering. But roster, neighborhood, link, twins and future will have to work together in ways that make sense and can be explained in a few unambiguous paragraphs.

**Comment by WardCunningham** [comment]
I am reminded of Jon's observation from happening #1
http://forage.ward.fed.wiki.org/view/urls-not-idempotent

I have come to understand his point to be that the system accumulates information that is not present in the URL that one might post or email to another. That information is in the neighborhood. Let's break down where we store information and how we use it. That will help us make good decisions for rosters and cohorts.

---

What the **Page** knows and does:

The page contains references to other sites in (at least) the journal and reference plugins. This information travels with the page as it is copied around the federation which makes it special. Links resolve to the origin or the page context. Where the origin overrides the page context we depend on flags within the page to make the page context visible.

What the **Lineup** knows and does:

The data handling plugins will "look to their left" for data from other pages. This makes lineup order significant. Plugins could look right too and we have considered that for creating dynamic feedback loops. The core javascript is only a passive bystander in these communications. I have high hopes for the lineup as the most user empowering concept in federated wiki so far.

What the **Tab** knows and does:

The origin's javascript provides reading and editing affordances to its user. The neighborhood is one of these services. A touch-based app might choose very different affordances consistent with capabilities of their intended devices. They would not be free to reinterpret page and lineup in novel ways.

When a link fails to find a page in its resolution context it delegates further user interaction to the 'future' plugin. This plugin explains why the link didn't succeed, offers to create the page, and, looks beyond the link resolution context to the tab's neighborhood in its effort to be helpful.

Similarly, when the neighborhood grows, the tab's javascript looks through pages in the lineup and annotates them with twin flags. 

---

Jon may not have yet understood the page vs. tab distinction made by links when he chose the technical term "idempotent" in the title of his observation about URLs. Likewise I had so internalized these three reservoirs of information that I had trouble understanding his association of URL and Lineup until we stepped through the case in a hangout.

I have also suggested in this issue that the activity and roster plugins might collude to show conversation-club-like focus in a variation of Recent Changes that bypasses the neighborhood choosing lineup associativity instead. This would be idempotent per Jon's post. But it might be even more terribly confusing to first time users trying to find their peers.

**Comment by thoka** [comment]
I think I understand the concept of **Page** and **Lineup**.
For **Tab** I need a pointer, where to read further ...

**Comment by WardCunningham** [comment]
When a browser tab opens it loads html and javascript from a site it calls the origin. That tab and the javascript it loads owns the user experience until some other page takes control. If you run federated wiki on your origin it should do well by you.

We say origin but we could just as well say tab.

**Comment by paul90** [comment]
Published as **\+ wiki-plugin-roster@0.1.0**

**Comment by WardCunningham** [comment]
Mike Caulfield explains two happening based use cases for roster/activity interaction.
https://www.youtube.com/watch?v=KfTk95mprdk
- Sites Page + Recent Changes => looking for new places to contribute to group activities
- Conversation Club => looking for recent contributions, especially by multiple authors

**Comment by WardCunningham** [comment]
The Roster plugin interprets a list of wiki sites and some additional formatting annotations. It can learn more about these sites by fetching content from them.
- Flag comes from a favicon.png fetched with a constructed image tag.
- Click goes to welcome-visitors in the site.
- Site size and last update date could come from fetching a sitemap
- Site owner name could come from welcome-visitors item 63ad2e58eecdd9e5
- Site owner bio could come from page linked by welcome-visitors item 63ad2e58eecdd9e5

A Roster plugin could offer to open a dynamically constructed (ghost) Sites page for some or all of the sites in the roster. It could cache bios and reload them if sitemaps show they should be updated.

**Comment by opn** [comment]
My thoughts on this. I have spend some time copy pasting large numbers of url's from lists generated from collections of reference links. My suggestions may be biased by this use-case. My first two frustrations were:
1. The site map does not load
2. Copy pasting URL's does not work ( I copied these from the flag of the reference links)

On the second point I was also disappointed that the links went now to the Welcome Page. Previously the links went to the "author page" - linked from the Welcome Page. It seem unecessary to restrict linking to the Welcome page in the Roster - an author should be able to provide a full link to a specific page if it suits their purpose (as it did in my case).

On the Neighbourhood loading issue, this can be off by default, but i am quite sure will often be needed by the majority of authors. The most flexible solution I can see is for the Roster Title lines to offer the option of "load neighbourhood" button to the far right of the Roster Title when rendered. This way it would be one click to load all the sites into the neighbourhood that come under the given title - and this would not over-clutter the screen.

Roster title syntax could control the behaviour of this loading / visibility of the button. So:

```
LOAD Wards Neighbourhood
ward.fed,wiki.org
forage.fed,wiki.org

AUTOLOAD Happening #3
....
```

Would render a title "Wards Neighbourhood" with a button to the far right allowing one-click loading, while "Happening #3" would be displayed as a title without a button, and the sites beneath the title would auto-load into the neighbourhood when the roster was displayed.

It may be useful to consider an "unload" function - as in a checkbox. But I suspect this may be overkill?

**Comment by WardCunningham** [comment]
Addressing @opn point 2, it might be possible to make an open TextEditor a drop zone for urls. Each plugin is responsible for editing though every one to date uses the editor provided by the core javascript. This plugin could register a drop handler, maybe even lib/drop.coffee, when it launches the core editor.

**Comment by opn** [comment]
Maybe my description was not orecise enough - I can copy paste a url - it is just that the code requires stripping out the "http://" part and does not utilise the path. This results in a lot of manual editing, so recognising a full urlband birmalising it would be a useful convenience.

More important is the ability to link to something other than Welcome Page.

**Comment by opn** [comment]
Sorry about mobile phone typos....

**Comment by WardCunningham** [comment]
Let's keep web urls at arm's length. Otherwise we're just making another web authoring tool. We've equated domain name to federation identity. We suggest, but do not require, that people write pages describing who they are and cite them on the one page, Welcome Visitors, that we know is present in every site.

Our drop logic is the point of entry for urls.

**Comment by WardCunningham** [comment]
This is my experiment with multi-page links in the style of conversation-club but opening within the current tab. The right-pointing triangles will open the welcome-visitor pages for every flag to its left. I omit the triangle when there are less than two flags on a given line.

![image](https://cloud.githubusercontent.com/assets/12127/7487222/36308fd6-f368-11e4-81cb-75e4121c4436.png)

The Roster markup treats blank lines as newlines. The various arrangements of sites, labels and blanks will make for a variety of arrangements when rendered on the page.

This feature should be coordinated with a similar capability in the now configurable Activity plugin. https://github.com/fedwiki/wiki-plugin-activity/pull/14

**Comment by paul90** [comment]
I wonder if it would not be better to just load the sitemap, for each site, rather than open the welcome-visitor pages?

**Comment by opn** [comment]
I second that. Site map loading is the main utility of the Roster.

**Comment by WardCunningham** [comment]
Yes. There is something not right about where we have gotten here.

Let me pose a question. I'll start with a pet theory. For the moment let us assume that thought moves through culture at three different scales.
- Solitude. Individuals think about past and future interactions with others.
- Conversation. Two to ten people expose their consciousness through language and gesture.
- Mobs. Large masses collect and respond with only the presence of others to confirm their action.

In federated wiki, ownership creates solitude, fork creates conversation, what will constitute the mob?

**Comment by opn** [comment]
The graph - or to be clear the visualisation of the graph. Now if I can
only get these SVG's working :)

**Comment by michaelarthurcaulfield** [comment]
For me roster is primarily about three really simple practical questions: initial connection, ongoing trust, and project management.

First, it's initial connection. Every time we set people up we lose them in the "connecting to other people process". I'd like connecting to an existing group to be as simple as connecting to an old listserv. "SUBSCRIBE shakespear-list". Bam. If this part is made simple, we can get to the more interesting stuff quicker. As it is, we lose most people in this step. Ward, I think we saw something smiliar at the Hackerspace event -- it just kills some of the forward momentum, and then you have to recover from that.

The second is ongoing trust. I see the use of rosters to be lists of people i work with and trust on specific issues. Ideally I'd like to mix a curated list someone else has with my own additions. I envision a world where if I want to learn something about physics I piggy-back on Brian Cox's physics roster, and trust the stuff in that it going to be pretty solid. It might even be nice when I go to a page to know this site is in X roster of mine (if that is an active roster).

(Rosters as a trust mechanism could also be a useful tool against harrassment, i.e. I'll use your roster if you keep pruning the trolls out. )

And finally there is the project management piece. I maybe actively collaborating with people in a class, or as part of a politically active group, or on a team in a company. And I may slice out a part of my day to say -- let's get caught up on the activity in that group or class. So I'd like to load that all up easily and go methodically through it. 

I don't know if this helps? Are these aims too diffuse? Too specific? Too unrelated?

**Comment by WardCunningham** [comment]
I finished coding up the lineup links on the airplane. Clicking the triangle opens multiple pages at once. If the pages are quickly accessible, like on your own laptop, then they just pop in. If you are in a hotel room with 300 ms ping time to anywhere then the pages stagger in, three or four a second. It has been suggested that this link should just load the sitemap. This behavior can be approximated by "canceling" the lineup, even before it is done, by hitting the browser's back button which is always fast.

The combination with recent Activity plugin enhancements is awesome. I was especially surprised at how nice the SORT by title worked in a large neighborhood. Here is a section of hangout #2 that I hadn't noticed before:

![image](https://cloud.githubusercontent.com/assets/12127/7665753/3a884b38-fb8c-11e4-95a4-cb2c1d30ceff.png)

A shift-click on a lineup link will pile pages even further to the right. This makes for some pretty dramatic scrolling. Maybe shift-clicking anything shouldn't scroll to the newly added pages. You know where they are going. Click up what ever you want and then scroll there yourself when you are good and ready.

Aside: I special cased 'localhost' to have any sites to look at while flying. I added tweaks to the parsing to handle port numbers too. This suggests that the markup might be a little too simplistic for every site name that we might ever see. Perhaps a SITE verb is in order to catch the remaining cases.

I'll have this together as a pull request soon. I'm sorry it has taken so long. I won't forget that I asked for comments. There is a lot of functionality here that we will need to just experiment with for a while before we fully understand it. Thanks for the patience.

**Comment by paul90** [comment]
#5 provides an alternative to adding pages to the lineup - with the ▶︎ links loading sitemaps.

**Comment by paul90** [comment]
Closing this issue as I don't see any outstanding items here

**Comment by WardCunningham** [comment]
The Roster plugin has become a regular part of my wiki experience. I will now think nice thoughts about this thread and its participants. Thank you.
